config/routes.rb
Rails.application.routes.draw do

  # Root Route
  root to: 'application#index'

  # Users Resource
  resources :users

  # Essie Colors API
  namespace :api do
    resources :colors
  end

  # Login Form
  get 'sessions/new' => 'sessions#new'
  # Login the user
  post 'sessions' => 'sessions#create', as: :login
  # Logout the user
  delete 'sessions' => 'sessions#destroy', as: :logout

end

app/models/color.rb
class Color < ActiveRecord::Base

	has_and_belongs_to_many :users

	def self.get_colors
		response = HTTParty.get('https://www.kimonolabs.com/api/dpq9elac?apikey=nSRHFLygw6rJNhaX3W2LKsLCwPPOudme')
		p response['results']['collection'][0]['color']['href']

		# response.each do |i|
		# 	category = ['results']['collection'][i]['color']['href']
		# end
		# p category
	end

end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password
	has_and_belongs_to_many :colors, dependent: :destroy

	validates :name, presence: true
	validates :email, presence: true
	validates :email, uniqueness: true
	validates :email, :email => {:strict_mode => true}
	validates :password, presence: true, length: { minimum: 8 }
		# unless: :skip_password_validation # Allows updating user information without updating password
	validates :password_confirmation, presence: true
		# unless: :skip_password_confirmation_validation # Allows updating user information without updating password
	validates :password_confirmation, confirmation: true

	# Allows updating user information without updating password
	attr_accessor :skip_password_validation, :skip_password_confirmation_validation

end

app/controllers/api/colors_controller.rb
class Api::ColorsController < ApplicationController
  before_action :authenticate
  before_action :set_color, only: [:show, :edit, :update, :destroy]

  # GET /colors
  # GET /colors.json
  def index
    @colors = Color.all
  end

  # GET /colors/1
  # GET /colors/1.json
  def show
  end

  # GET /colors/new
  def new
    @color = Color.new
  end

  # GET /colors/1/edit
  def edit
    @color = Color.find(params[:id])
  end

  # POST /colors
  # POST /colors.json
  def create
    @color = Color.new(color_params)

    respond_to do |format|
      if @color.save
        format.html { redirect_to @color, notice: 'Color was successfully created.' }
        format.json { render :show, status: :created, location: @color }
      else
        format.html { render :new }
        format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colors/1
  # PATCH/PUT /colors/1.json
  def update
    respond_to do |format|
      if @color.update(color_params)
        format.html { redirect_to @color, notice: 'Color was successfully updated.' }
        format.json { render :show, status: :ok, location: @color }
      else
        format.html { render :edit }
        format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colors/1
  # DELETE /colors/1.json
  def destroy
    @color.destroy
    respond_to do |format|
      format.html { redirect_to colors_url, notice: 'Color was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_color
      @color = Color.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def color_params
      params.require(:color).permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :authenticate

  def index
  end

  def current_user
  	User.find_by(id: session[:current_user])
  end

  def authenticate
  	redirect_to sessions_new_path unless current_user
  end

end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  before_action :authenticate
  before_action :set_color, only: [:show, :edit, :update, :destroy]

  # GET /colors
  # GET /colors.json
  def index
    @colors = Color.all
  end

  # GET /colors/1
  # GET /colors/1.json
  def show
  end

  # GET /colors/new
  def new
    @color = Color.new
  end

  # GET /colors/1/edit
  def edit
  end

  # POST /colors
  # POST /colors.json
  def create
    @color = Color.new(color_params)

    respond_to do |format|
      if @color.save
        format.html { redirect_to @color, notice: 'Color was successfully created.' }
        format.json { render :show, status: :created, location: @color }
      else
        format.html { render :new }
        format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colors/1
  # PATCH/PUT /colors/1.json
  def update
    respond_to do |format|
      if @color.update(color_params)
        format.html { redirect_to @color, notice: 'Color was successfully updated.' }
        format.json { render :show, status: :ok, location: @color }
      else
        format.html { render :edit }
        format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colors/1
  # DELETE /colors/1.json
  def destroy
    @color.destroy
    respond_to do |format|
      format.html { redirect_to colors_url, notice: 'Color was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_color
      @color = Color.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def color_params
      params.require(:color).permit(:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    email = params[:email]
    password = params[:password]
    user = User.find_by(email: email)

    if user && user.authenticate(password)
      session[:current_user] = user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    session[:current_user] = nil
    redirect_to sessions_new_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(
        :name,
        :email,
        :password,
        :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/colors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Colors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @colors.each do |color| %>
      <tr>
        <td><%= color.name %></td>
        <td><%= link_to 'Show', color %></td>
        <td><%= link_to 'Edit', edit_api_color_path(color) %></td>
        <td><%= link_to 'Destroy', color, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Color', new_api_color_path %>

app/views/colors/new.html.erb
<h1>New Color</h1>

<%= render 'form' %>

<%= link_to 'Back', colors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ruby on Nails &#x1f485;</title>
  <%= favicon_link_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<nav class="grey-text white z-depth-0">
  <div class="nav-wrapper">
    <%= link_to "Ruby on Nails", api_colors_path, :class => 'brand-logo' %>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <% if current_user %>
        <li><%= current_user.name%></li>
        <li><%= link_to "Logout", logout_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Sign Up', new_user_path %></li>
        <li><%= link_to 'Login', sessions_new_path %></li>
      <% end %>
    </ul>
  </div>
</nav>


<div class="container">
  <%= yield %>
</div>
<footer class="page-footer red lighten-5">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="grey-text">About Ruby on Nails</h5>
        <p class="grey-text text-lighten-1">This app was built by a lady dev named Emily so she could have a side project based entirely on a pun, learn Material Design, and help herself with the regular dilemma of picking a nail polish color.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="grey-text">More from Emily</h5>
        <ul>
          <li><a class="grey-text text-lighten-1" href="#!"><%= icon('desktop') %>Website</a></li>
          <li><a class="grey-text text-lighten-1" href="#!"><%= icon('github') %>GitHub</a></li>
          <li><a class="grey-text text-lighten-1" href="#!"><%= icon('instagram') %>Instagram</a></li>
          <li><a class="grey-text text-lighten-1" href="#!"><%= icon('twitter') %>Twitter</a></li>
          <li><a class="grey-text text-lighten-1" href="#!"><%= icon('behance') %>Behance</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright grey-text text-darken-1">
    <div class="container center-align">
    Made with <%= icon('heart-o') %> in Brooklyn
    </div>
  </div>
</footer>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>